---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---



```{r libraries, warning=FALSE, include=FALSE}
library(tidyverse)
library(rasterVis)
library(raster)
library(OpenImageR)
library(RImagePalette)
library(jpeg)
library(sp)
library(lattice)
library(latticeExtra)
library(egg)
```


```{r define_functions}
img_into_dataframe <- function(image_path, cutoff_threshold) {
  # Extract the file name (regexp pattern matches any characters not a slash ([^/]+) followed by .jpg at the end of the string $
  file_name <- str_extract(image_path, pattern = '([^/]+)\\.jpg$')
  file_name <- sub('\\.jpg$', '', file_name) # replace .jpg with ''
  
  # Read in the image
  img <- readJPEG(image_path)
  
  # Flatten the image into a vector (1D array)
  img_vector <- as.vector(img)
  
  # Convert that vector into a single column dataframe.
  img_df <- data.frame(pixel_intensity = img_vector) %>% 
      # Filter out all the gray background pixels. According to histograms, there's a big distribution around .25 and the rest are located after .50. .40 should be a good cutoff point for images manipulated by the ExG vegetative index. 
      filter(pixel_intensity > cutoff_threshold) %>% 
      # Add a column that specifies which file it came from
      mutate(file_name = file_name)
  
  message(paste("Dataframe created for:", file_name))
  
  # Return a dataframe 
  return(img_df)
  
}

save_boxplot <- function(img_df, image_path, outputdir) {
  
  # Build the plot
  plot <- ggplot(img_df, aes(x = pixel_intensity, y = 1)) +
    geom_boxplot(fill = 'olivedrab') +
    coord_flip() +
    labs(
      x = 'Pixel Luminosity',
      y = file_name
    ) +
    theme(
      panel.background = element_blank(),
      axis.ticks = element_blank(),
      axis.text.x = element_blank(),
      panel.grid = element_blank(),
      panel.grid.major.y = element_line('gray75')
      )
  
  plot_name <- paste0('boxplot_', image_path)
  
  ggsave(filename=plot_name, plot=plot, path=outputdir, width=1.25, height = 8)
  
  message(paste("Plot saved for:", file_name))

  
}

save_first_boxplot <- function(img_df, image_path, outputdir) {
  
  # Build the plot
  plot <- ggplot(img_df, aes(x = pixel_intensity, y = 1)) +
    geom_boxplot(fill = 'olivedrab') +
    coord_flip() +
    labs(
      x = 'Pixel Intensity',
      y = file_name
    ) +
    theme(
      panel.background = element_blank(),
      axis.ticks = element_blank(),
      axis.text.x = element_blank(),
      panel.grid = element_blank(),
      panel.grid.major.y = element_line('gray75')
      )
  
  
  plot_name <- paste0('boxplot_', image_path)
  
  ggsave(filename=plot_name, plot=plot, path=outputdir, width=1.25, height = 8)
  
  message(paste("Plot saved for:", file_name))
}

```


```{r}
# Save file paths in the RGBVI results folder in a vector
# Set directory to the correct folder
setwd('results/vi_rgbvi')

# Save list of image file names in a variable
file_name_list <- dir(pattern = 'jpg')

# Make a dataframe out of the file_name_list
file_name_df <- data.frame(filename = file_name_list) %>% 
  # Concatenate beginning of file path to each file 
  mutate(filename = paste('results/vi_rgbvi/', filename, sep=''))

# Run img_into_dataframe function on every file in the folder
img_df <- sapply(file_name_df$filename, img_into_dataframe)
```

CURSED CHUNK OF CODE HANDLE WITH CARE
```{r}
# Set directory to the correct folder
setwd('results/vi_rgbvi')

# Save list of image file names in a variable
filenames <- dir(pattern = 'jpg')

# Remove image_0 from the list (it's different from the others because it uses a y-axis label. Won't be necessary when plots are arranged in a grid)
filenames <- filenames[-1]

# img_dfs <- lapply(filenames, img_into_dataframe)



# Combine all dataframes into one. Running this crashed rstudio. 
# img_df <- do.call(rbind, img_dfs)

```


```{r render_first_boxplot, fig.width=1.5, fig.height=5}

file_name = 'image_0.jpg'

img_df <- img_into_dataframe_into_boxplot(file_name)

plot <- ggplot(img_df, aes(x = pixel_intensity, y = 1)) +
  geom_boxplot(fill = 'olivedrab') +
  coord_flip() +
  labs(
    x = 'Pixel Intensity',
    y = file_name
  ) +
  theme(
    panel.background = element_blank(),
    axis.ticks = element_blank(),
    axis.text.x = element_blank(),
    panel.grid = element_blank(),
    panel.grid.major.y = element_line('gray75')
    )

plot_name <- paste0('boxplot_image_', 0, '.jpg')
path <- '../vi_rgbvi_boxplots'

ggsave(filename=plot_name, plot=plot, path=path, width=1.5, height = 8)


```

```{r run_remaining_plots, fig.width=1.5, fig.height=5}

# Set directory to the correct folder
setwd('results/mask_experiment')

# Save list of image file names in a variable
filenames <- dir(pattern = 'jpg')

# Apply function to all the images in the test folder
img_dfs <- lapply(filenames, img_into_dataframe_into_boxplot)


# Test new image on one image
img_into_dataframe_into_boxplot(file_name="image_6.jpg", path='../vi_rgbvi_boxplots_greenhouse')

# Now do it on the rest. heaven help my computer. 
lapply(filenames, img_into_dataframe_into_boxplot)

 

```
TEST ON SINGLE BOXPLOT

```{r test_on_single_boxplot}
image_path <- 'results/mask_experiment_vi_greenhouse/image_8.jpg'
outputdir <- 'results/greenhouse_photos_thresholded_boxplots'

# Use .40 threshold because that's the cutoff between background and leaf in images mapped to the ExG vegetative index
img_df <- img_into_dataframe(image_path, cutoff_threshold = .40)

# ggplot(img_df, aes(x=pixel_intensity)) +
#   geom_histogram()

save_first_boxplot(img_df, image_path, outputdir)

```


```{r apply_to_all_greenhouse_imgs}
folder <- 'results/mask_experiment'

# Save list of image file names in a variable
full_filenames <- list.files(folder, full.names = TRUE)

outputdir <- 'results/greenhouse_photos_thresholded_boxplots'

# Apply function to all the files in that list. Godspeed, little one. 
lapply(full_filenames, img_into_dataframe_into_boxplot, outputdir = outputdir)

```
Try stitching all the dataframes together again because it would make everything so much easier to work with
```{r}
folder <- 'results/mask_experiment_vi_greenhouse'

# Save list of image file names in a variable
image_paths <- list.files(folder, full.names = TRUE)

# Apply df creation function to all paths in the list
img_dfs <- lapply(image_paths, img_into_dataframe, cutoff_threshold=0.4)

# Stitch all the dataframes into one
all_greenhouse_img_df <- do.call(rbind, img_dfs)

```

