---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---



```{r libraries, warning=FALSE, include=FALSE}
library(tidyverse)
library(rasterVis)
library(raster)
library(OpenImageR)
library(RImagePalette)
library(jpeg)
library(sp)
library(lattice)
library(latticeExtra)
library(egg)
library(ggbeeswarm)
```


```{r define_function}
img_into_dataframe_into_boxplot <- function(filename) {
  
  # Read in the image
  img <- readJPEG(filename)
  
  # Flatten the image into a vector (1D array)
  img_vector <- as.vector(img)
  
  # Convert that vector into a single column dataframe.
  img_df <- data.frame(pixel_intensity = img_vector)
  
  
  
  return(img_df)
  
}
```


```{r}
# Save file paths in the RGBVI results folder in a vector
# Set directory to the correct folder
setwd('results/vi_rgbvi')

# Save list of image file names in a variable
file_name_list <- dir(pattern = 'jpg')

# Make a dataframe out of the file_name_list
file_name_df <- data.frame(filename = file_name_list) %>% 
  # Concatenate beginning of file path to each file 
  mutate(filename = paste('results/vi_rgbvi/', filename, sep=''))

# Run img_into_dataframe function on every file in the folder
img_df <- sapply(file_name_df$filename, img_into_dataframe)
```

CURSED CHUNK OF CODE HANDLE WITH CARE
```{r}
# Set directory to the correct folder
setwd('results/vi_rgbvi')

# Save list of image file names in a variable
filenames <- dir(pattern = 'jpg')

img_dfs <- lapply(filenames, img_into_dataframe)



# Combine all dataframes into one. Running this crashed rstudio. 
# img_df <- do.call(rbind, img_dfs)

```


```{r render_first_boxplot, fig.width=1.5, fig.height=5}

filename = 'image_0.jpg'

img_df <- img_into_dataframe_into_boxplot(filename)

ggplot(img_df, aes(x = pixel_intensity, y = 1)) +
  geom_boxplot(fill = 'olivedrab') +
  coord_flip() +
  labs(
    x = 'Pixel Intensity',
    y = filename
  ) +
  theme(
    panel.background = element_blank(),
    axis.ticks = element_blank(),
    axis.text.x = element_blank(),
    panel.grid = element_blank(),
    panel.grid.major.y = element_line('gray75')
    )


```

```{r run_remaining_plots,fig.width=1.5, fig.height=5}



```

